# docker exec -ti oraclexe sqlplus sys/password@//localhost:1521/XE as sysdba

CREATE USER HLF IDENTIFIED BY HLF;

GRANT CONNECT, RESOURCE TO HLF;

GRANT CREATE SESSION TO HLF;

SELECT 1 from dual;

CREATE TABLE HLF.BC_VALID_TX_WRITE_SET (
BLOCK NUMBER(6) NOT NULL,
TXSEQ NUMBER(6) NOT NULL,
ITEM  NUMBER(6) NOT NULL,
KEY   VARCHAR2(100) NOT NULL,
VALUE VARCHAR2(4000),
IS_DELETE CHAR(1)
)
TABLESPACE USERS

SELECT * FROM HLF.BC_VALID_TX_WRITE_SET

INSERT INTO HLF.BC_VALID_TX_WRITE_SET VALUES (1,0,0,'akey','avalue',null)

COMMIT

SELECT * FROM HLF.BC_VALID_TX_WRITE_SET

DELETE HLF.BC_VALID_TX_WRITE_SET

TRUNCATE TABLE HLF.BC_VALID_TX_WRITE_SET

SELECT count(*) FROM HLF.BC_VALID_TX_WRITE_SET

DROP TABLE HLF.BC_VALID_TX_WRITE_SET

DROP INDEX HLF.BC_VALID_TX_WRITE_SET_UK

CREATE UNIQUE INDEX HLF.BC_VALID_TX_WRITE_SET_UK
ON HLF.BC_VALID_TX_WRITE_SET(BLOCK, TXSEQ, ITEM)
TABLESPACE USERS

SELECT * FROM (
SELECT x.*, count(*) over(PARTITION BY BLOCK, TXSEQ, ITEM) AS COUNT_KEY
FROM HLF.BC_VALID_TX_WRITE_SET x
) WHERE COUNT_KEY > 1

